# Kyverno Installation for GKE Autopilot
# This file installs Kyverno using the official Helm chart manifests

# For GKE Autopilot, we use a simplified installation
# In production, consider using Helm for more control:
# helm repo add kyverno https://kyverno.github.io/kyverno/
# helm install kyverno kyverno/kyverno -n kyverno --create-namespace

---
# Namespace for Kyverno
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: policy-demo

---
# Kyverno CRDs and installation
# Note: For a full installation, apply the official release:
# kubectl apply -f https://github.com/kyverno/kyverno/releases/download/v1.11.4/install.yaml

# ServiceAccount for Kyverno
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-admission-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-background-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-cleanup-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-reports-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: reports-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno

---
# ConfigMap for Kyverno configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno
  namespace: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
data:
  # Exclude kyverno namespace from policy enforcement
  resourceFilters: |
    [*,kyverno,*]
    [Event,*,*]
    [*,kube-system,*]
    [*,kube-public,*]
    [*,kube-node-lease,*]
    [Node,*,*]
    [APIService,*,*]
    [TokenReview,*,*]
    [SubjectAccessReview,*,*]
    [SelfSubjectAccessReview,*,*]
    [Binding,*,*]
    [ReplicaSet,*,*]
    [AdmissionReport,*,*]
    [ClusterAdmissionReport,*,*]
    [BackgroundScanReport,*,*]
    [ClusterBackgroundScanReport,*,*]
  # Enable webhooks
  webhooks: |
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          - kyverno
          - kube-system
          - kube-public
          - kube-node-lease
  # Generate success events
  generateSuccessEvents: "false"

---
# Note: For a complete Kyverno installation on GKE Autopilot, run:
# kubectl apply -f https://github.com/kyverno/kyverno/releases/download/v1.11.4/install.yaml
#
# Or use Helm:
# helm repo add kyverno https://kyverno.github.io/kyverno/
# helm install kyverno kyverno/kyverno -n kyverno --create-namespace \
#   --set admissionController.replicas=3 \
#   --set backgroundController.replicas=2 \
#   --set cleanupController.replicas=2 \
#   --set reportsController.replicas=2