# Gatekeeper ConstraintTemplate: Require Labels
# This template defines the Rego policy for requiring specific labels

apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
  annotations:
    metadata.gatekeeper.sh/title: "Required Labels"
    metadata.gatekeeper.sh/version: 1.0.0
    description: >-
      Requires resources to contain specified labels, with values matching
      provided regular expressions.
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
              description: Custom message to display when validation fails
            labels:
              type: array
              description: List of required labels
              items:
                type: object
                properties:
                  key:
                    type: string
                    description: The required label key
                  allowedRegex:
                    type: string
                    description: >-
                      If specified, a regular expression the label value must match.
                      The value must contain at least one match for the regular expression.
                required:
                  - key
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels

        import future.keywords.in

        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
            provided := {label | input.review.object.metadata.labels[label]}
            required := {label | label := input.parameters.labels[_].key}
            missing := required - provided
            count(missing) > 0
            msg := sprintf("You must provide labels: %v", [missing])
        }

        violation[{"msg": msg}] {
            value := input.review.object.metadata.labels[key]
            expected := input.parameters.labels[_]
            expected.key == key
            expected.allowedRegex != ""
            not regex.match(expected.allowedRegex, value)
            msg := sprintf("Label <%v: %v> does not match regex %v", [key, value, expected.allowedRegex])
        }

---
# ConstraintTemplate for requiring labels on Pod templates in Deployments
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabelsdeployment
  annotations:
    metadata.gatekeeper.sh/title: "Required Labels on Deployments"
    metadata.gatekeeper.sh/version: 1.0.0
    description: >-
      Requires Deployments to contain specified labels on both the Deployment
      metadata and the Pod template.
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabelsDeployment
      validation:
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
            labels:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                required:
                  - key
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabelsdeployment

        import future.keywords.in

        # Check deployment metadata labels
        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
            input.review.object.kind == "Deployment"
            provided := {label | input.review.object.metadata.labels[label]}
            required := {label | label := input.parameters.labels[_].key}
            missing := required - provided
            count(missing) > 0
            msg := sprintf("Deployment must have labels: %v", [missing])
        }

        # Check pod template labels
        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
            input.review.object.kind == "Deployment"
            provided := {label | input.review.object.spec.template.metadata.labels[label]}
            required := {label | label := input.parameters.labels[_].key}
            missing := required - provided
            count(missing) > 0
            msg := sprintf("Deployment Pod template must have labels: %v", [missing])
        }